# @Date:   2018-10-18T11:05:57-06:00
# @Last modified time: 2018-10-18T11:33:45-06:00



version: 2
jobs:
  build:
    # Add image here 
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-npm-deps-{{ checksum "package.json" }}
        - v1-npm-deps
    - run:
        # Add commands here
    - save_cache:
        key: v1-npm-deps-{{ checksum "package.json" }}
        paths:
        - node_modules
workflows:
  version: 2
  workflow:
    jobs:
    - build
